//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// C4IMap.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_C4IMapTYPE                  130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDR_PASTE_MENU                  151
#define ID_SORTPROPERTIES               152
#define IDR_WINDOWS_MENU                153
#define ID_PROPERTIES1                  154
#define ID_PROPERTIES2                  155
#define ID_EXPAND_ALL                   156
#define IDS_FILE_VIEW                   157
#define IDS_CLASS_VIEW                  158
#define IDS_OUTPUT_WND                  159
#define IDS_PROPERTIES_WND              160
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_COP_VIEW                    178
#define IDB_CLASS_VIEW_24               179
#define IDB_COP_VIEW_24                 180
#define IDR_MENU_IMAGES                 181
#define IDR_POPUP_MAPVIEW               182
#define IDB_MENU_IMAGES_24              183
#define ID_TOOLS_MACRO                  184
#define IDR_OUTPUT_POPUP                185
#define IDR_PROPERTIES                  186
#define IDB_PROPERTIES_HC               187
#define IDR_THEME_MENU                  189
#define ID_SET_STYLE                    190
#define ID_VIEW_APPLOOK_WIN_2000        191
#define ID_VIEW_APPLOOK_OFF_XP          192
#define ID_VIEW_APPLOOK_WIN_XP          193
#define ID_VIEW_APPLOOK_OFF_2003        194
#define ID_VIEW_APPLOOK_VS_2005         195
#define ID_VIEW_APPLOOK_VS_2008         196
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   197
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  198
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 199
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   200
#define ID_VIEW_APPLOOK_WINDOWS_7       201
#define IDS_OUTLOOKBAR                  202
#define IDS_RIBBON_FILE                 203
#define IDS_RIBBON_NEW                  204
#define IDS_RIBBON_OPEN                 205
#define IDS_RIBBON_SAVE                 206
#define IDS_RIBBON_SAVEAS               207
#define IDS_RIBBON_PRINT                208
#define IDS_RIBBON_PRINT_LABEL          209
#define IDS_RIBBON_PRINT_QUICK          210
#define IDS_RIBBON_PRINT_PREVIEW        211
#define IDS_RIBBON_PRINT_SETUP          212
#define IDS_RIBBON_CLOSE                213
#define IDS_RIBBON_RECENT_DOCS          214
#define IDS_RIBBON_EXIT                 215
#define IDS_RIBBON_HOME                 216
#define IDS_RIBBON_CLIPBOARD            217
#define IDS_RIBBON_PASTE                218
#define IDS_RIBBON_CUT                  219
#define IDS_RIBBON_COPY                 220
#define IDS_RIBBON_SELECTALL            221
#define IDS_RIBBON_CAPTIONBAR           222
#define IDS_RIBBON_WINDOW               223
#define IDS_RIBBON_WINDOWS              224
#define IDS_RIBBON_STYLE                225
#define IDS_RIBBON_STYLE_TIP            226
#define IDS_RIBBON_STYLE_DESC           227
#define IDS_RIBBON_STATUSBAR            228
#define IDS_RIBBON_VIEW                 229
#define IDS_BUILD_TAB                   230
#define IDS_DEBUG_TAB                   231
#define IDS_FIND_TAB                    232
#define IDS_EXPLORER                    235
#define IDS_EDIT_MENU                   236
#define IDR_RIBBON                      237
#define IDD_MAP_GENERATOR               238
#define IDR_SORT_COP                    239
#define IDR_POPUP_SORT_COP              240
#define IDR_POPUP_OUTPUT                241
#define IDR_INDEXMAP_TOOLBAR            242
#define IDB_INDEXMAP_TOOLBAR_24         243
#define IDB_SORT_COP_24                 245
#define IDI_COPLAYER_VIEW               247
#define IDI_COPLAYER_VIEW_HC            248
#define IDI_COPITEM_VIEW                249
#define IDI_COPITEM_VIEW_HC             250
#define IDI_COPTYPE_VIEW                251
#define IDI_COPTYPE_VIEW_HC             252
#define IDR_POPUP_SEARCH                253
#define ID_VIEW_CAPTION_BAR             254
#define IDB_INFO                        255
#define IDB_PNG_RBAR_VIEW_L             258
#define IDB_PNG_RBAR_VIEW_S             259
#define IDB_PNG_RBAR_SCREEN_S           260
#define IDB_PNG_RBAR_SCREEN_L           261
#define IDC_CURSOR_DEFAULT              262
#define IDC_CURSOR_ZOOMIN               263
#define IDC_CURSOR_ZOOMOUT              264
#define IDC_CURSOR_PANNING              265
#define IDC_CURSOR_ROTATE               266
#define IDC_CURSOR_RECT                 267
#define IDC_CURSOR_INFO                 268
#define IDC_CURSOR_CIRCLE               269
#define IDC_CURSOR_POLYGON              270
#define IDC_CURSOR_LENGTH               271
#define IDC_CURSOR_AREA                 272
#define IDC_CURSOR_SECTION              273
#define IDC_CURSOR_VISIBLE              274
#define IDC_CURSOR_TERRAIN              275
#define IDC_CURSOR2                     276
#define IDC_CURSOR_COORD_INPUT          277
#define IDB_PNG_3DRIBBON                278
#define IDB_PNG_RBAR_DRAW_L             279
#define IDB_PNG_RBAR_DRAW_S             280
#define IDB_OVERLAY_DRAW_LINE           281
#define IDB_OVERLAY_DRAW_LINEBOW        282
#define IDB_OVERLAY_DRAW_LINEDESH       283
#define IDB_OVERLAY_DRAW_LINEWIDTH      284
#define IDB_OVERLAY_DRAW_RECT           285
#define IDB_OVERLAY_DRAW_DEFAULT        286
#define IDB_OVERLAY_DRAW_QUICKSTYLE     287
#define IDR_FONT                        288
#define IDR_FONT_ALIGN                  289
#define IDB_PNG_RBAR_ANALYSIS_S         290
#define IDB_PNG_RBAR_ANALYSIS_L         291
#define IDR_FONT_ALIGNY                 292
#define IDR_STATUS_DISCONNECT           293
#define IDB_OVERLAYVIEW_TREE            294
#define IDR_POPUP_MAPORDER              295
#define IDB_OVERLAYVIEW_TOOLBAR_24      296
#define IDB_OVERLAYVIEW_TREE_24         297
#define IDR_OVERLAYVIEW_TOOLBAR         298
#define IDR_HELP_MENU                   299
#define ID_INDICATOR_LATLONG            301
#define ID_INDICATOR_SCALE              302
#define ID_INDICATOR_MODE               303
#define ID_INDICATOR_TIME               304
#define ID_RAWS                         305
#define ID_VIEW_FRAME                   308
#define ID_COP_ADD_MEMBER_FUNCTION      309
#define ID_COP_ADD_MEMBER_VARIABLE      310
#define ID_COP_DEFINITION               311
#define ID_COP_PROPERTIES               312
#define ID_NEW_FOLDER_COP               313
#define ID_SORT_MENU_COP                314
#define ID_SORTING_GROUPBYTYPE_COP      315
#define ID_SORTING_SORTALPHABETIC_COP   316
#define ID_SORTING_SORTBYTYPE_COP       317
#define ID_SORTING_SORTBYACCESS_COP     318
#define ID_VIEW_COPLAYERVIEW            319
#define ID_VIEW_COPTYPEVIEW             320
#define ID_VIEW_COPITEMVIEW             321
#define ID_POPUP_OUTPUT_COPY            322
#define IDS_COPLAYER_VIEW               323
#define ID_POPUP_OUTPUT_CLEAR           324
#define IDS_COPTYPE_VIEW                325
#define ID_POPUP_OUTPUT_ALLCLEAR        326
#define IDS_COPITEM_VIEW                327
#define ID_POPUP_OUTPUT_MOVE            328
#define ID_MAPROPERTIESWND              329
#define ID_MAP_MANAGERWND               331
#define IDB_MAPVIEW_TREE                332
#define IDB_MAPVIEW_TREE_24             333
#define ID_OVERLAY_VIEWWND              334
#define IDB_MAPORDER_LIST               335
#define IDB_MAPORDER_LIST_24            336
#define IDB_TREE_CHECKBOX               337
#define ID_INDEXMAP_WND                 338
#define IDC_CHK_RASTER                  338
#define IDC_CHK_SATELLITE               339
#define IDC_CHK_VECTOR                  340
#define IDC_COP_LISTCTRL_LAYER          341
#define IDC_COP_TREECTRL_TYPE           342
#define IDC_COP_LISTCTRL_ITEM           343
#define IDS_CAPTION_BUTTON              344
#define IDS_CAPTION_BUTTON_TIP          345
#define ID_TOOLS_OPTIONS                346
#define IDS_CAPTION_TEXT                347
#define IDS_CAPTION_IMAGE_TIP           348
#define IDS_CAPTION_IMAGE_TEXT          349
#define IDB_TRK_CIRCLE                  350
#define IDI_CLOSE                       351
#define IDR_POPUP                       352
#define IDC_BTN_CREATE                  1001
#define IDC_BUTTON1                     1002
#define IDC_BTN_OVERLAY_LINE_DASH_STYLE_DASHDOTDOT 1006
#define IDC_EDT_OVERLAY_LINE_BLEND      1277
#define IDC_EDT_OVERLAY_LINE_THICKNESS  1278
#define IDC_BTN_OVERLAY_TEXT_OK         1279
#define IDC_RADIO_OVERLAY_FILL          1331
#define IDC_RADIO_OVERLAY_LINE          1333
#define IDB_BTN_LEFT                    1373
#define IDB_BTN_LEFT_CLICK              1374
#define IDB_BTN_RIGHT                   1375
#define IDB_BTN_RIGHT_CLICK             1376
#define IDB_BTN_CLICK_CENTER            1377
#define IDB_BTN_CLICK_LEFT              1378
#define IDB_BTN_CLICK_RIGHT             1379
#define IDB_BTN_DEFAULT_CENTER          1380
#define IDB_BTN_DEFAULT_LEFT            1381
#define IDB_BTN_DEFAULT_RIGHT           1382
#define IDB_BTN_DISABLE_CENTER          1383
#define IDB_BTN_DISABLE_LEFT            1384
#define IDB_BTN_DISABLE_RIGHT           1385
#define IDB_BTN_FOCUS_CENTER            1386
#define IDB_BTN_FOCUS_LEFT              1387
#define IDB_BTN_FOCUS_RIGHT             1388
#define IDB_BTN_OVER_CENTER             1389
#define IDB_BTN_OVER_LEFT               1390
#define IDB_BTN_OVER_RIGHT              1391
#define IDC_STATIC_RIGHT_BOTTOM_LATDD   1515
#define IDC_STATIC_RIGHT_BOTTOM_LATMM   1516
#define IDC_STATIC_RIGHT_BOTTOM_LATSS   1517
#define IDC_STATIC_RIGHT_BOTTOM_LONGDD  1518
#define IDC_STATIC_RIGHT_BOTTOM_LONGMM  1519
#define IDC_STATIC_RIGHT_BOTTOM_LONGSS  1520
#define IDD_DLG_OVERLAYER_CONTROL       1521
#define IDD_DLG_OBJECT_DRAW_ORDER_CONTROL 1603
#define IDD_DLG_OVERLAY_EDIT_OBJECT     1610
#define IDD_DLG_OVERLAY_EDIT_OBJECT_POINT 1611
#define IDD_DLG_OVERLAY_LINE_DASH_STYLE 1612
#define IDD_DLG_OVERLAY_PROPERTY        1614
#define IDD_DLG_OVERLAY_TEXT_EDIT       1616
#define IDB_OVERLAY_DIAMOND             1639
#define IDB_OVERLAY_CURVELINE           1640
#define IDB_OVERLAY_ELLIPSE             1641
#define IDB_OVERLAY_ARC                 1642
#define IDB_OVERLAY_PIE                 1643
#define IDB_OVERLAY_LINE                1644
#define IDB_OVERLAY_POLYLINE            1645
#define IDB_OVERLAY_LINKEDLINE          1647
#define IDB_OVERLAY_LINKED_MULTILINE    1648
#define IDB_OVERLAY_LINKED_CURVE        1649
#define IDB_OVERLAY_TEXT                1650
#define IDB_OVERLAY_IMAGE               1651
#define IDB_OVERLAY_ROUND_RECT          1652
#define IDB_OVERLAY_TRIANGLE            1653
#define IDB_OVERLAY_RECT                1654
#define IDB_OVERLAY_PENTAGON            1655
#define IDB_OVERLAY_SIXANGLE            1656
#define IDB_OVERLAY_EIGHTANGLE          1657
#define IDB_OVERLAY_GRID                1658
#define IDB_OVERLAY_LAYERDLG            1659
#define IDB_OVERLAY_POLYGON             1660
#define IDD_DLG_ADA_FILTERS             1661
#define IDB_OVERLAY_ARC_OFF             1662
#define IDB_OVERLAY_DIAMOND_OFF         1663
#define IDB_OVERLAY_CURVELINE_OFF       1664
#define IDB_OVERLAY_EIGHTANGLE_OFF      1665
#define IDB_OVERLAY_ELLIPSE_OFF         1666
#define IDB_OVERLAY_GRID_OFF            1667
#define IDB_OVERLAY_IMAGE_OFF           1668
#define IDB_OVERLAY_LAYERDLG_OFF        1669
#define IDB_OVERLAY_LINE_OFF            1670
#define IDB_OVERLAY_LINKED_CURVE_OFF    1671
#define IDB_OVERLAY_LINKED_MULTILINE_OFF 1672
#define IDB_OVERLAY_LINKEDLINE_OFF      1673
#define IDB_OVERLAY_PENTAGON_OFF        1674
#define IDB_OVERLAY_PIE_OFF             1675
#define IDB_OVERLAY_POLYGON_OFF         1676
#define IDB_OVERLAY_POLYLINE_OFF        1677
#define IDB_OVERLAY_RECT_OFF            1678
#define IDB_OVERLAY_ROUND_RECT_OFF      1679
#define IDB_OVERLAY_SIXANGLE_OFF        1680
#define IDB_OVERLAY_TEXT_OFF            1681
#define IDB_OVERLAY_TRIANGLE_OFF        1682
#define IDC_BTN_OBJECT_ELLIPSE          2601
#define IDC_BTN_OBJECT_ARC              2602
#define IDC_BTN_OBJECT_PIE              2603
#define IDC_BTN_OBJECT_POLYLINE         2605
#define IDC_BTN_OBJECT_CURVE            2606
#define IDC_BTN_OBJECT_POLYGON          2607
#define IDC_BTN_OBJECT_TEXT             2611
#define IDC_BTN_OBJECT_DIAMOND          2612
#define IDC_BTN_OBJECT_PICTURE          2613
#define IDC_BTN_OBJECT_ROUND_RECT       2614
#define IDC_BTN_OBJECT_PENTAGON         2617
#define IDC_BTN_OBJECT_SIXANGLE         2618
#define IDC_BTN_OBJECT_EIGHTANGLE       2619
#define IDC_LIST_OVERLAY_LAYER          2620
#define IDC_BTN_OVERLAY_SHOW_GRID2      2621
#define IDC_BTN_OVERLAY_SHOW_GRID       2622
#define IDC_LIST_OVERLAY_OBJECTS        2627
#define IDC_BTN_LAYER_MOVE_BOTTOM2      2628
#define IDC_BTN_LAYER_DELETE_ALL        2629
#define IDC_BTN_OBJECT_MOVE_TOP         2630
#define IDC_BTN_LAYER_LOAD              2631
#define IDC_BTN_OBJECT_MOVE_UP          2632
#define IDC_BTN_LAYER_DELETE_ALL3       2633
#define IDC_BTN_LAYER_SAVE              2634
#define IDC_BTN_OBJECT_MOVE_DOWN        2635
#define IDC_BTN_OBJECT_MOVE_BOTTOM      2636
#define IDC_BTN_ADD_LAYER               2637
#define IDC_EDT_ADD_LAYER_NAME          2638
#define IDC_BTN_OBJECT_SELECTED_OBJECT_DELETE 2639
#define IDC_EDT_SELECTEDLAYER_NAME      2640
#define IDC_SPIN_OVERLAY_FILL_BLEND     2641
#define IDC_SLIDER_OVERLAY_FILL_BLEND   2642
#define IDC_SLIDER_OVERLAY_LINE_BLEND   2643
#define IDC_SPIN_OVERLAY_LINE_BLEND     2644
#define IDC_SPIN_OVERLAY_LINE_THICKNESS 2645
#define IDC_STATIC_OVERLAY_FILL_COLOR   2646
#define IDC_STATIC_OVERLAY_LINE_COLOR   2647
#define IDC_RADIO_OVERLAY_NO_FILL       2648
#define IDC_RADIO_OVERLAY_NO_LINE       2649
#define IDC_BTN_OVERLAY_LINE_COLOR      2650
#define IDC_EDT_OVERLAY_FILL_BLEND      2651
#define IDC_BTN_OVERLAY_LINE_DASH_STYLE_SOLID 2652
#define IDC_EDIT_TRACK_OPTIONS_KIND_OF_TRACK 2653
#define IDC_EDIT_CENTER_BY_INPUT_START_LAT 2654
#define IDC_EDIT_CENTER_BY_INPUT_START_LNG 2655
#define IDC_BTN_OVERLAY_PROPERTY_OK     2656
#define IDC_BTN_OVERLAY_PROPERTY_CANCEL 2657
#define IDC_LIST_KJCCS_UNIT_INFO        2658
#define IDC_LIST_NAVY_TRACK_INFO        2660
#define IDC_EDT_OVERLAY_TEXT_EDIT       2661
#define IDC_CMB_OVERLAY_TEXT_FONT_SIZE  2662
#define IDC_BTN_OVERLAY_TEXT_COLOR      2663
#define IDC_CMB_OVERLAY_TEXT_FONT_STYLE 2664
#define IDC_SLIDER_OVERLAY_TEXT_TRANSPARENT 2665
#define IDC_CMB_OVERLAY_TEXT_FONT_STYLE2 2666
#define IDC_CMB_OVERLAY_TEXT_FONT       2667
#define IDC_STATIC_OVERLAY_TEXT_BLEND   2668
#define IDC_STATIC_OVERLAY_OBJECT_SELECTED_OBJECT_TYPE 2669
#define IDC_STATIC_OVERLAY_OBJECT_SELECTED_OBJECT_ID 2670
#define IDC_EDT_OVERLAY_EDIT_OBJECT_ROTATION 2671
#define IDC_EDT_OVERLAY_EDIT_OBJECT_LEFT_TOP_DEGREE_LAT 2672
#define IDC_EDT_OVERLAY_EDIT_OBJECT_LEFT_TOP_DEGREE_LNG 2673
#define IDC_EDT_OVERLAY_EDIT_OBJECT_LEFT_TOP_DMS_LAT_D 2674
#define IDC_EDT_OVERLAY_EDIT_OBJECT_LEFT_TOP_DMS_LAT_M 2675
#define IDC_EDT_OVERLAY_EDIT_OBJECT_LEFT_TOP_DMS_LAT_S 2676
#define IDC_EDT_OVERLAY_EDIT_OBJECT_LEFT_TOP_DMS_LNG_D 2677
#define IDC_EDT_OVERLAY_EDIT_OBJECT_LEFT_TOP_DMS_LNG_M 2678
#define IDC_EDT_OVERLAY_EDIT_OBJECT_LEFT_TOP_DMS_LNG_S 2679
#define IDC_RADIO_OVERLAY_EDIT_OBJECT_SELECT_LAT_LNG_DEGREE 2680
#define IDC_RADIO_OVERLAY_EDIT_OBJECT_SELECT_LAT_LNG_DMS 2681
#define IDC_BTN_OVERLAY_EDIT_OBJECT_MGRS 2682
#define IDC_EDIT_OVERLAY_OBJECT_LEFT_TOP_MGRS 2683
#define IDC_EDIT_OVERLAY_OBJECT_RIGHT_BOTTOM_MGRS 2684
#define IDC_EDT_OVERLAY_EDIT_OBJECT_RIGHT_BOTTOM_LAT_DEGREE 2685
#define IDC_EDT_OVERLAY_EDIT_OBJECT_RIGHT_BOTTOM_LNG_DEGREE 2686
#define IDC_EDT_OVERLAY_EDIT_OBJECT_RIGHT_BOTTOM_DMS_LAT_M 2687
#define IDC_EDT_OVERLAY_EDIT_OBJECT_RIGHT_BOTTOM_DMS_LAT_S 2688
#define IDC_EDT_OVERLAY_EDIT_OBJECT_RIGHT_BOTTOM_DMS_LNG_M 2689
#define IDC_EDT_OVERLAY_EDIT_OBJECT_RIGHT_BOTTOM_DMS_LNG_D 2690
#define IDC_EDT_OVERLAY_EDIT_OBJECT_RIGHT_BOTTOM_DMS_LNG_S 2691
#define IDC_EDT_OVERLAY_EDIT_OBJECT_RIGHT_BOTTOM_DMS_LAT_D 2700
#define IDC_STATIC_LEFT_TOP_LATDD       2701
#define IDC_STATIC_LEFT_TOP_LONGDD      2702
#define IDC_STATIC_LEFT_TOP_LONGMM      2703
#define IDC_STATIC_LEFT_TOP_LATMM       2704
#define IDC_STATIC_LEFT_TOP_LONGSS      2705
#define IDC_STATIC_LEFT_TOP_LATSS       2706
#define IDC_BTN_OVERLAY_EDIT_OBJECT_LAT_LNG 2707
#define IDC_EDIT_OVERLAY_OBJECT_LEFT_TOP_GEOREF 2708
#define IDC_BTN_OVERLAY_EDIT_OBJECT_GEOREF 2709
#define IDC_EDIT_OVERLAY_OBJECT_RIGHT_BOTTOM_GEOREF 2710
#define IDC_BTN_OVERLAY_EDIT_OBJECT_POINT_LAT_LNG 2711
#define IDC_EDT_OVERLAY_EDIT_OBJECT_POINT_DEGREE_LAT 2712
#define IDC_EDT_OVERLAY_EDIT_OBJECT_POINT_DEGREE_LNG 2713
#define IDC_EDT_OVERLAY_EDIT_OBJECT_POINT_DMS_LAT_D 2714
#define IDC_EDT_OVERLAY_EDIT_OBJECT_POINT_DMS_LNG_D 2715
#define IDC_EDT_OVERLAY_EDIT_OBJECT_POINT_DMS_LAT_M 2716
#define IDC_EDT_OVERLAY_EDIT_OBJECT_POINT_DMS_LNG_M 2717
#define IDC_EDT_OVERLAY_EDIT_OBJECT_POINT_DMS_LAT_S 2718
#define IDC_EDT_OVERLAY_EDIT_OBJECT_POINT_DMS_LNG_S 2719
#define IDC_RADIO_OVERLAY_EDIT_OBJECT_POINT_SELECT_LAT_LNG_DEGREE 2720
#define IDC_RADIO_OVERLAY_EDIT_OBJECT_POINT_SELECT_LAT_LNG_DMS 2721
#define IDC_BTN_OVERLAY_EDIT_OBJECT_POINT_MGRS 2722
#define IDC_BTN_OVERLAY_EDIT_OBJECT_POINT_GEOREF 2723
#define IDC_EDIT_OVERLAY_OBJECT_POINT_GEOREF 2724
#define IDC_EDIT_OVERLAY_OBJECT_POINT_MGRS 2725
#define IDC_STATIC_POINT_LATDD          2726
#define IDC_STATIC_POINT_LATMM          2727
#define IDC_STATIC_POINT_LATSS          2728
#define IDC_STATIC_POINT_LONGDD         2729
#define IDC_STATIC_POINT_LONGMM         2730
#define IDC_STATIC_POINT_LONGSS         2731
#define IDC_CMB_OVERLAY_PROPERTY_LINE_DASH_KIND 2732
#define IDC_CMB_OVERLAY_PROPERTY_LINE_START_KIND 2733
#define IDC_CMB_OVERLAY_PROPERTY_LINE_END_KIND 2734
#define IDC_BTN_OVERLAY_LINE_DASH_STYLE_DOT 2735
#define IDC_BTN_DELETE_LAYER            2736
#define IDC_BTN_OVERLAY_FILL_COLOR      2737
#define IDC_BTN_OVERLAY_LINE_DASH_STYLE_DASH 2738
#define IDC_BTN_OVERLAY_LINE_DASH_STYLE_DASHDOT 2739
#define IDC_SEL_FILE_BUTTON             2740
#define IDC_STATIC_OVERLAY_LINE_THICK   2741
#define IDC_STATIC_OVERLAY_EDIT_TEXT_PREVIEW 2742
#define IDC_LIST_COMPARE_TRACK_INFO     2743
#define IDC_BTN_COMPARE_TRACK_INFO_DELETE_SELECTED_TRACK 2744
#define IDC_BTN_COMPARE_TRACK_INFO_DELETE_ALL 2745
#define IDC_STATIC_COMPARE_TRACK_INFO_SELECTED_TRACK 2746
#define IDC_BUTTON_ASRS_SERVER_CONNECT  2747
#define IDC_STATIC_COMPARE_TRACK_INFO_RECORDING_STATUS 2748
#define IDC_TREE_RECFFOLDER             2751
#define IDC_BUTTON_SELECT_ALL           2755
#define IDC_PROGRESS_RECEIVE_STATUS     2756
#define IDC_RECEIVING_FILENAME          2757
#define IDC_BUTTON_SELECTDN             2758
#define IDC_TREE_FILELIST               2759
#define IDC_LIST_TREE_FILE_LIST         2760
#define IDC_RADIO_SELECT_DOWNLOAD       2761
#define IDC_RADIO_BULK_DOWNLOAD         2762
#define IDC_DATETIMEPICKER_PAST         2763
#define IDC_DATETIMEPICKER_PRESENT      2764
#define IDC_EDIT_RECEIIVING_FILENAME    2765
#define IDC_MENU_REPLAY_FILE_DOWNLOAD   2766
#define IDC_STATIC_KJCCS_REPORT_COUNT   2767
#define IDC_STATIC_MIMS_INFO_REPORT_TOTAL_COUNT 2768
#define IDC_STATIC_NAVY_TRACK_INFO_REPORT_TOTAL_COUNT 2769
#define IDOK_STATUS                     2770
#define IDC_LIST_NORTH_TRACK_NUMBER     2771
#define IDC_BTN_BUTTON_NORTHTRACK_SAVE  2772
#define IDC_RADIO_POLARIS               2774
#define IDC_RADIO_SELECT_2MCRC          2775
#define IDC_RADIO_SELECT_POLARIS        2776
#define IDC_PROGRESS_RECV_STATUS        2777
#define IDC_EDIT_RECV_STATUS            2778
#define IDC_BUTTON_LOAD_NORTH_TRACK     2779
#define IDC_REPLAY_BW_10MIN             2780
#define IDC_REPLAY_FW_10MIN             2781
#define IDC_CHECK_UNDERLINE             2782
#define IDC_CHECK_STRIKEOUT             2783
#define IDC_CHECK_SPEED                 2785
#define IDC_CHECK_HEAD                  2786
#define IDC_CHECK_ALT                   2787
#define IDC_LIST_TRACKINFO              2788
#define IDC_CHEMICAL_LIST               2789
#define IDC_LOCALSYM_LIST               2790
#define IDC_AIRSYM_LIST                 2791
#define IDC_COMMONSYM_LIST              2792
#define IDC_VIEWINFO_LIST               2793
#define IDC_BUTTON_TRKRF                2794
#define IDC_RADIO_TIME                  2795
#define IDC_RADIO_INFO                  2796
#define IDC_RADIO_MAP                   2799
#define IDC_RADIO_DBMAP                 2800
#define IDC_CHECK_LABEL                 2801
#define IDC_TREE_NORTH_FILTERS          2802
#define IDC_RADIO_X72                   2805
#define IDC_TREE_ADA_FILTERS            2806
#define IDC_CITYFILTER_TREE             2808
#define IDC_CITYINFO_LIST               2809
#define IDC_BUTTON_BASE                 2810
#define IDC_BUTTON_BASE1                2811
#define IDC_BUTTON_BASE2                2815
#define IDC_BUTTON_BASE3                2816
#define IDC_BUTTON_BASE4                2817
#define IDC_BUTTON_BASE5                2818
#define IDC_BUTTON_BASE6                2819
#define IDC_BUTTON_BASE7                2820
#define IDC_BUTTON_BASE8                2821
#define IDC_BUTTON_BASE9                2822
#define IDC_BUTTON_BASE10               2823
#define IDC_BUTTON_BASE11               2824
#define IDC_BUTTON_BASE12               2825
#define IDC_BUTTON_BASE13               2826
#define IDC_BUTTON_BASE14               2827
#define IDC_BUTTON_BASE15               2828
#define IDC_BUTTON_BASE16               2829
#define IDC_BUTTON_BASE17               2830
#define IDC_BUTTON_BASE18               2845
#define IDC_BUTTON_BASE19               2846
#define IDC_BUTTON_BASE20               2847
#define IDC_BUTTON_BASE21               2848
#define IDC_BUTTON_BASE22               2849
#define IDC_BUTTON_BASE23               2850
#define IDC_BUTTON_BASE24               2851
#define IDC_BUTTON_BASE25               2852
#define IDC_BUTTON_BASE26               2853
#define IDC_BUTTON_BASE27               2854
#define IDC_BUTTON_BASE28               2855
#define IDC_BUTTON_BASE29               2856
#define IDC_BUTTON_BASE30               2857
#define IDC_BUTTON_BASE31               2858
#define IDC_BUTTON_BASE32               2859
#define IDC_BUTTON_BASE33               2860
#define IDC_BUTTON_BASE34               2861
#define IDC_BUTTON_BASE35               2862
#define IDC_BUTTON_BASE36               2863
#define IDC_BUTTON_BASE37               2864
#define IDC_BUTTON_BASE38               2865
#define IDC_BUTTON_BASE39               2866
#define IDC_BUTTON_BASE40               2867
#define IDC_BUTTON_BASE41               2868
#define IDC_BUTTON_BASE42               2869
#define IDC_BUTTON_BASE43               2870
#define IDC_BUTTON_BASE44               2871
#define IDC_BUTTON_BASE45               2872
#define IDC_BUTTON_BASE46               2873
#define IDC_BUTTON_BASE47               2874
#define IDC_BUTTON_BASE48               2875
#define IDC_BUTTON_BASE49               2876
#define IDC_BUTTON_BASE50               2877
#define IDC_BUTTON_BASE51               2878
#define IDC_BUTTON_BASE52               2879
#define IDC_BUTTON_BASE53               2880
#define IDC_BUTTON_BASE54               2881
#define IDC_BUTTON_BASE55               2882
#define IDC_BUTTON_BASE56               2883
#define IDC_BUTTON_BASE57               2884
#define IDC_BUTTON_BASE58               2885
#define IDC_BUTTON_BASE59               2886
#define IDC_BUTTON_BASE60               2887
#define IDC_BUTTON_BASE61               2888
#define IDC_BUTTON_BASE62               2889
#define IDC_BUTTON_BASE63               2890
#define IDC_BUTTON_BASE64               2891
#define IDC_BUTTON_BASE65               2892
#define IDC_BUTTON_BASE66               2893
#define IDC_BUTTON_BASE67               2894
#define IDC_BUTTON_BASE68               2895
#define IDC_BUTTON_BASE69               2896
#define IDC_BUTTON_BASE70               2897
#define ID_RESET_LIST                   2899
#define IDC_BUTTON_LOAD                 2902
#define IDC_LIST_TITLE                  2903
#define IDC_LIST_VALUES                 2904
#define IDC_COMBO_DATE                  2905
#define IDC_SLIDER_B                    2907
#define IDC_CHECK_B_TYPE                2908
#define IDC_LIST_SHR                    2909
#define IDC_BUTTON_SHR_DOWN             2911
#define IDC_LIST3                       2912
#define IDC_SLIDER2                     2914
#define IDC_BUTTON2                     2915
#define IDC_BTN_LAYER_REFRESH           2916
#define IDC_BTN_OBJECT_LINE             2920
#define IDC_BTN_OBJECT_LINKED_LINE      2924
#define IDC_BTN_OBJECT_LINKED_MULTI_LINE 2925
#define IDC_BTN_OBJECT_LINKED_MULTI_CURVE 2926
#define IDC_BTN_OBJECT_TRIANGLE         2931
#define IDC_BTN_OBJECT_RECT             2932
#define IDC_BTN_LAYER_MOVE_TOP          2939
#define IDC_BTN_LAYER_MOVE_UP           2940
#define IDC_BTN_LAYER_MOVE_BOTTOM       2941
#define IDC_BTN_LAYER_MOVE_DOWN         2942
#define IDM_POPTRK_RANGE_RING           10098
#define IDM_POPGRD_RANGE_RING           10101
#define IDM_POPTRK_DETAIL               10104
#define ID_POPSYM_RANGE_RING            10105
#define IDM_POPSYM_RANGE_RING           10106
#define IDM_POPSP_RANGE_CIRCLE          10109
#define IDM_POPTRK_BEARING_RANGE        10111
#define IDM_POPGRD_BEARING_RANGE        10112
#define ID_POPSYM_BEARING_RANGE         10113
#define IDM_POPSP_BEARING_RANGE         10114
#define IDM_PRIVATE_BIB_LABEL           10121
#define IDM_POPGRD_POINT_DISPLAY        10122
#define IDM_POPTRK_ALLHISTORY           10124
#define IDM_POPTRK_ALLHISTORY_DELETE    10127
#define ID_POPTRK_HCallsign             10128
#define ID_MENUITEM33182                10168
#define ID_CC_DEFAULT                   10173
#define ID_CC_ORANGE                    10174
#define ID_CC_PURPLE                    10175
#define ID_CC_BROWN                     10176
#define ID_CC_WHITE                     10177
#define ID_CC_BLUE                      10178
#define IDM_POPOVERLAY_PROPERTY         10179
#define IDM_POPOVERLAY_MOVE_BOTTOM      10180
#define IDM_POPOVERLAY_MOVE_TOP         10181
#define IDM_POPOVERLAY_GROUP            10211
#define IDM_POPOVERLAY_GROUP_RELEASE    10212
#define IDM_POPOVERLAY_EDIT_OBJECT      10213
#define ID_POPTRK_COMPARE_TRACK_TARGET  10214
#define ID_POPTRK_COMPARE_TRACK_STOP    10215
#define ID_POPTRK_COMPARE_TRACK_BASE    10217
#define ID_POPTRK_COMPARE_TRACK_WINDOW  10220
#define ID_OBJ_INFO                     10917
#define ID_OBJ_DELETE                   10918
#define ID_OBJ_COMMAND                  10919
#define ID_MENU_DETOXI_CALC             10933
#define ID_PROP_OBJ_ZI                  10943
#define ID_PROP_OBJ_ZO                  10944
#define ID_PROP_OBJ_FONT                10945
#define ID_PROP_OBJ_CHO                 10946
#define ID_PROP_OBJ_CHRO                10947
#define ID_MENU_1_AO                    10950
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_MINIMAP_BUTTON               32771
#define IDC_CHECK_SATELLITE             32772
#define ID_BTN_MAPGENERATER             32773
#define IDC_CHECK_RASTER                32774
#define IDC_CHECK_SHAPE                 32775
#define IDC_CHECK_DTED                  32776
#define IDC_LIST_TEXT                   32777
#define ID_MAPVIEW_AUTO_ON              32783
#define ID_MAPVIEW_AUTO_OFF             32785
#define ID_MAPORDER_TOP                 32787
#define ID_MAPORDER_UP                  32789
#define ID_MAPORDER_DOWN                32791
#define ID_MAPORDER_BOTTOM              32793
#define ID_RIBBON_TEST_INDATA_AIR       32814
#define ID_RIBBON_TEST_INDATA_SEA       32815
#define ID_RIBBON_TEST_INDATA_MIL       32816
#define ID_RIBBON_TEST_INDATA_TBM       32817
#define ID_RIBBON_TEST_INDATA_NBC       32818
#define ID_RIBBON_TEST_INDATA_TIS       32819
#define ID_RIBBON_TEST_INDATA_PT        32820
#define ID_RIBBON_TEST_INDATA_PL        32821
#define ID_RIBBON_TEST_INDATA_PG        32822
#define ID_RIBBON_TEST_DELDATA_ALL      32823
#define ID_RIBBON_TEST_DELDATA_EACH     32824
#define ID_RIBBON_TEST_SEARCHDATA_AERA  32825
#define ID_RIBBON_TEST_SEARCHDATA_HISTORY 32826
#define ID_RIBBON_TEST_SEARCHDATA_AEARTRACE 32827
#define ID_RIBBON_TEST_SEARCHDATA_AEARHISTORY 32828
#define ID_RIBBON_TEST_SEARCHDATA_HISTORYTRACE 32829
#define ID_RIBBON_TEST_SEARCHDATA_CLEAR 32830
#define ID_RIBBON_TEST_FILEDATA_SAVE    32831
#define ID_RIBBON_TEST_FILEDATA_OPEN    32832
#define ID_MENU_MOUSE_BASE              32833
#define ID_MENU_MOUSE_ZOOMIN            32834
#define ID_MENU_MOUSE_ZOOMOUT           32835
#define ID_MENU_MOUSE_MOVE              32836
#define ID_MENU_MAP_UNDO                32837
#define ID_MENU_MAP_REDO                32838
#define ID_MENU_MAP_INIT                32839
#define ID_MENU_MAP_SELECT              32840
#define ID_MENU_MAP_ROTATE              32841
#define ID_MENU_MAP_SCALE               32842
#define ID_MENU_MAP_RASTER_ONOFF        32843
#define ID_MENU_MAP_DTED_ONOFF          32844
#define ID_MENU_BOOKMARK                32845
#define ID_MENU_ADD_BOOKMARK            32846
#define ID_MENU_MOVE_BOOKMARK           32847
#define ID_MENU_DELETE_BOOKMARK         32848
#define ID_MENU_PROJECTION              32849
#define ID_MENU_PROJECTION_GEO          32850
#define ID_MENU_PROJECTION_UTM          32851
#define ID_MENU_PROJECTION_MER          32852
#define ID_MENU_PROJECTION_LCC          32853
#define ID_MENU_PROJECTION_STE          32854
#define ID_MENU_PROJECTION_EQU          32855
#define ID_MENU_COORDINATE_INFO         32856
#define ID_MENU_COORDINATE_MOVE         32857
#define ID_MENU_COORDGRID_SET           32858
#define ID_MENU_BRIGHT_SLIDER           32859
#define ID_MENU_BRIGHT_EDIT             32860
#define ID_MENU_CONTRAST_SLIDER         32861
#define ID_MENU_CONTRAST_EDIT           32862
#define ID_MENU_BRICON_INIT             32863
#define ID_MENU_SAVE_CLIPBOARD          32864
#define ID_MENU_SAVE_IMAGEFILE          32865
#define ID_MENU_PRINT_SELECT_PRIVIEW    32866
#define ID_MENU_PRINT_ALL_PRIVIEW       32867
#define ID_MENU_MAPMANAGER_ONOFF        32868
#define ID_MENU_OVERVIEW_ONOFF          32869
#define ID_MENU_MAPPROP_ONOFF           32870
#define ID_MENU_OVERPROP_ONOFF          32871
#define ID_MENU_INDEXMAP_ONOFF          32872
#define ID_MENU_OUTPUT_ONOFF            32873
#define ID_MENU_SEARCH_CLEAR            32874
#define ID_MENU_SEARCH_POINT            32875
#define ID_MENU_SEARCH_AREA_TARGET      32876
#define ID_MENU_SEARCH_AREA_SHAPE       32877
#define ID_MENU_SEARCH_AREA_COLOR       32878
#define ID_MENU_SEARCH_AREA             32879
#define ID_MENU_SEARCH_MAP_LAYER        32880
#define ID_MENU_SEARCH_MAP_FIELD        32881
#define ID_MENU_SEARCH_MAP_INPUT        32882
#define ID_MENU_SEARCH_MAP              32883
#define ID_MENU_ANALYSIS_CLEAR          32884
#define ID_MENU_ANALYSIS_DISTANCE       32885
#define ID_MENU_ANALYSIS_AREA           32886
#define ID_MENU_ANALYSIS_SECTION        32887
#define ID_MENU_ANALYSIS_VISIBLE_RANGE  32888
#define ID_MENU_ANALYSIS_VISIBLE_HEIGHT 32889
#define ID_MENU_ANALYSIS_VISIBLE_COLOR  32890
#define ID_MENU_ANALYSIS_VISIBLE_SELECT 32891
#define ID_MENU_ANALYSIS_RADIUS_INTERVAL 32892
#define ID_MENU_ANALYSIS_RADIUS_RANGE   32893
#define ID_MENU_ANALYSIS_RADIUS_WIDTH   32894
#define ID_MENU_ANALYSIS_RADIUS_COLOR   32895
#define ID_MENU_ANALYSIS_RADIUS_SELECT  32896
#define ID_MENU_ANALYSIS_RADIUS_INPUT   32897
#define ID_MENU_OVERLAY_NEW             32898
#define ID_MENU_OVERLAY_SAVE            32899
#define ID_MENU_OVERLAY_OPEN            32900
#define ID_MENU_OVERLAY_DELETE          32901
#define ID_MENU_OVERLAY_GRADATION       32902
#define ID_MENU_OVERLAY_UNDO            32903
#define ID_MENU_OVERLAY_REDO            32904
#define ID_MENU_OVERLAY_PASTE           32905
#define ID_MENU_OVERLAY_CUT             32906
#define ID_MENU_OVERLAY_COPY            32907
#define ID_OVERLAYVIEW_OVERLAY_TOP      32908
#define ID_OVERLAYVIEW_OVERLAY_UP       32909
#define ID_OVERLAYVIEW_OVERLAY_DOWN     32910
#define ID_OVERLAYVIEW_OVERLAY_BOTTOM   32911
#define ID_OVERLAYVIEW_OVERLAY_DELETE   32912
#define ID_MENU_OVERLAY_LINE_COLOR      32928
#define ID_MENU_OVERLAY_FILL_COLOR      32929
#define ID_MENU_OVERLAY_PATTERN_COLOR   32930
#define ID_MENU_OVERLAY_LINE_WIDTH      32931
#define ID_MENU_OVERLAY_FILL_USE        32932
#define ID_MENU_OVERLAY_PATTERN_USE     32933
#define ID_MENU_OVERLAY_LINE_STYLE      32934
#define ID_MENU_OVERLAY_TRANS_USE       32935
#define ID_MENU_OVERLAY_PATTERN_STYLE   32936
#define ID_MENU_OVERLAY_TEXT_KIND       32937
#define ID_MENU_OVERLAY_TEXT_SIZE       32938
#define ID_MENU_OVERLAY_TEXT_COLOR      32939
#define ID_MENU_OVERLAY_LINE_WIDTH_0    32940
#define ID_MENU_OVERLAY_LINE_WIDTH_1    32941
#define ID_MENU_OVERLAY_LINE_WIDTH_2    32942
#define ID_MENU_OVERLAY_LINE_WIDTH_3    32943
#define ID_MENU_OVERLAY_LINE_WIDTH_4    32944
#define ID_MENU_OVERLAY_LINE_WIDTH_5    32945
#define ID_MENU_OVERLAY_LINE_WIDTH_6    32946
#define ID_MENU_OVERLAY_LINE_WIDTH_7    32947
#define ID_MENU_OVERLAY_LINE_WIDTH_8    32948
#define ID_MENU_OVERLAY_LINE_WIDTH_9    32949
#define ID_MENU_OVERLAY_LINE_WIDTH_10   32950
#define ID_MENU_OVERLAY_LINE_STYLE_0    32951
#define ID_MENU_OVERLAY_LINE_STYLE_1    32952
#define ID_MENU_OVERLAY_LINE_STYLE_2    32953
#define ID_MENU_OVERLAY_LINE_STYLE_3    32954
#define ID_MENU_OVERLAY_LINE_STYLE_4    32955
#define ID_MENU_OVERLAY_PATTERN_STYLE_0 32956
#define ID_MENU_OVERLAY_PATTERN_STYLE_1 32957
#define ID_MENU_OVERLAY_PATTERN_STYLE_2 32958
#define ID_MENU_OVERLAY_PATTERN_STYLE_3 32959
#define ID_MENU_OVERLAY_PATTERN_STYLE_4 32960
#define ID_MENU_OVERLAY_PATTERN_STYLE_5 32961
#define ID_MENU_OVERLAY_TEXT_BOLD       32962
#define ID_MENU_OVERLAY_TEXT_ITALIC     32963
#define ID_MENU_OVERLAY_TEXT_UNDERLINE  32964
#define ID_MENU_OVERLAY_TEXT_STRIKEOUT  32965
#define ID_MENU_OVERLAY_TEXT_ALIGNLEFT  32966
#define ID_MENU_OVERLAY_TEXT_ALIGNCENTER 32967
#define ID_MENU_OVERLAY_TEXT_ALIGNRIGHT 32968
#define ID_MENU_MAP_SCALE_CURRENT       32969
#define ID_MENU_MAP_SCALE_MIN           32970
#define ID_MENU_MAP_SCALE_MAX           32971
#define ID_MENU_MAP_SCALE_ZOOM          32972
#define ID_MENU_MAP_AUTOCHANGE          32973
#define ID_MENU_MAP_AUTOCHANGESET       32974
#define ID_RIBBON_COP_SELFREE           32975
#define ID_RIBBON_COP_SHOW              32976
#define ID_RIBBON_COP_IMPO_PATROL       32978
#define ID_RIBBON_COP_IMPO_LIST         32979
#define ID_RIBBON_COP_ALWS_LIST         32980
#define ID_RIBBON_COP_SYM_DEFAULT       32981
#define ID_RIBBON_COP_SYM_ZOOM_SLIDER   32982
#define ID_RIBBON_COP_SYM_COLORONOFF    32983
#define ID_RIBBON_COP_SYM_SIMPLE        32984
#define ID_RIBBON_COP_SYM_AUTOSIZE      32985
#define ID_RIBBON_COP_SYM_COLOR         32986
#define ID_RIBBON_COP_SYM_BRIGHT_SLIDER 32987
#define ID_RIBBON_COP_SYM_FILLWATER     32988
#define ID_RIBBON_COP_SYM_OVERLAY_NEW   32989
#define ID_RIBBON_COP_SYM_OVERLAY_INSERT 32990
#define ID_RIBBON_COP_SYM_REFASH        32991
#define ID_RIBBON_COP_LAYERLIST         32992
#define ID_RIBBON_COP_TYPELIST          32993
#define ID_RIBBON_COP_ITEMLIST          32994
#define ID_RIBBON_ANALSYS_DISTANCE      32995
#define ID_RIBBON_ANALSYS_AREA          32996
#define ID_RIBBON_ANALSYS_SECTION       32997
#define ID_RIBBON_ANALSYS_VISIBLE       32998
#define ID_RIBBON_ANALSYS_TERRAIN       32999
#define ID_INDEXMAP_BASE                33012
#define ID_INDEXMAP_ZOOMIN              33013
#define ID_INDEXMAP_ZOOMOUT             33014
#define ID_INDEXMAP_PANNING             33015
#define ID_INDEXMAP_SETTING             33016
#define ID_RIBBON_COP_SYM_ZOOM_SLIDER_EDIT 33043
#define ID_RIBBON_COP_SYM_BRIGHT_EDIT   33044
#define ID_RIBBON_COP_SYM_FILLWATER_PWD 33045
#define ID_RIBBON_COP_SYM_FILLWATER_IFF 33046
#define ID_RIBBON_COP_SYM_INFO_HIDE     33047
#define ID_RIBBON_COP_SYM_INFO_ADD      33048
#define ID_RIBBON_COP_SYM_INFO_HISTORY  33049
#define ID_RIBBON_COP_SYM_INFO_ABILITY  33050
#define ID_RIBBON_COP_SEARCH_CLEAR      33052
#define ID_RIBBON_COP_SEARCH_LAYER      33053
#define ID_RIBBON_COP_SEARCH_FIELD      33054
#define ID_RIBBON_COP_SEARCH_COLOR      33055
#define ID_RIBBON_COP_SEARCH_TYPE       33056
#define ID_RIBBON_COP_SEARCH_WORD       33057
#define ID_RIBBON_COP_SEARCH_AREA       33058
#define ID_RIBBON_COP_SEARCH_ATTR       33059
#define ID_RIBBON_OVERLAY_LAYERLIST     33060
#define ID_RIBBON_OVERLAY_ITEMLIST      33061
#define ID_RIBBON_OVERLAY_DRAW_GALLERY  33062
#define ID_RIBBON_OVERLAY_QUICKSTYLE_GALLERY 33063
#define ID_RIBBON_OVERLAY_SORT_GALLERY  33064
#define ID_RIBBON_OVERLAY_GRADATION_GALLERY 33065
#define ID_RIBBON_OVERLAY_GRADATION_ETC_GALLERY 33066
#define ID_RIBBON_OVERLAY_TEXTURE_GALLERY 33067
#define ID_RIBBON_OVERLAY_PATTERN_GALLERY 33068
#define ID_RIBBON_3D_MESH               33069
#define ID_RIBBON_3D_RENDER             33070
#define ID_RIBBON_3D_EFFECT             33071
#define ID_RIBBON_3D_DTEDRATE_EDIT      33072
#define ID_RIBBON_3D_FOGDEPTH_EDIT      33073
#define ID_RIBBON_3D_SUN_EDIT           33074
#define ID_RIBBON_3D_SPEED_EDIT         33075
#define ID_RIBBON_OVERLAY_TEXTURE_ETC_GALLERY 33076
#define ID_MENU_OVERLAY_LINE_WIDTH_COLOR 33077
#define ID_MENU_OVERLAY_LINE_WIDTH_ETC_COLOR 33078
#define ID_MENU_OVERLAY_LINE_DESH_COLOR 33079
#define ID_MENU_OVERLAY_LINE_DESH_ETC_COLOR 33080
#define ID_MENU_OVERLAY_LINE_BOW_COLOR  33081
#define ID_MENU_OVERLAY_LINE_BOW_ETC_COLOR 33082
#define ID_MENU_OVERLAY_FILL_IMAGE      33083
#define ID_MENU_OVERLAY_FILL_TYPE       33084
#define ID_MENU_OVERLAY_FILL_TYPE_0     33085
#define ID_MENU_OVERLAY_FILL_TYPE_1     33086
#define ID_MENU_OVERLAY_FILL_TYPE_2     33087
#define ID_MENU_OVERLAY_FILL_TYPE_3     33088
#define ID_MENU_OVERLAY_FILL_TYPE_4     33089
#define ID_MENU_OVERLAY_HATCH_STYLE_0   33090
#define ID_MENU_OVERLAY_HATCH_STYLE_1   33091
#define ID_MENU_OVERLAY_HATCH_STYLE_2   33092
#define ID_MENU_OVERLAY_HATCH_STYLE_3   33093
#define ID_MENU_OVERLAY_HATCH_STYLE_4   33094
#define ID_MENU_OVERLAY_HATCH_STYLE_5   33095
#define ID_MENU_OVERLAY_HATCH_STYLE_6   33096
#define ID_MENU_OVERLAY_HATCH_STYLE_7   33097
#define ID_MENU_OVERLAY_HATCH_STYLE_8   33098
#define ID_MENU_OVERLAY_HATCH_STYLE_9   33099
#define ID_MENU_OVERLAY_HATCH_STYLE_10  33100
#define ID_MENU_OVERLAY_HATCH_STYLE_11  33101
#define ID_MENU_OVERLAY_HATCH_STYLE_12  33102
#define ID_MENU_OVERLAY_HATCH_STYLE_13  33103
#define ID_MENU_OVERLAY_HATCH_STYLE_14  33104
#define ID_MENU_OVERLAY_HATCH_STYLE_15  33105
#define ID_MENU_OVERLAY_HATCH_STYLE_16  33106
#define ID_MENU_OVERLAY_HATCH_STYLE_17  33107
#define ID_MENU_OVERLAY_HATCH_STYLE_18  33108
#define ID_MENU_OVERLAY_HATCH_STYLE_19  33109
#define ID_MENU_OVERLAY_HATCH_STYLE_20  33110
#define ID_MENU_OVERLAY_HATCH_STYLE_21  33111
#define ID_MENU_OVERLAY_HATCH_STYLE_22  33112
#define ID_MENU_OVERLAY_HATCH_STYLE_23  33113
#define ID_MENU_OVERLAY_HATCH_STYLE_24  33114
#define ID_MENU_OVERLAY_HATCH_STYLE_25  33115
#define ID_MENU_OVERLAY_HATCH_STYLE_26  33116
#define ID_MENU_OVERLAY_HATCH_STYLE_27  33117
#define ID_MENU_OVERLAY_HATCH_STYLE_28  33118
#define ID_MENU_OVERLAY_HATCH_STYLE_29  33119
#define ID_MENU_OVERLAY_HATCH_STYLE_30  33120
#define ID_MENU_OVERLAY_HATCH_STYLE_31  33121
#define ID_MENU_OVERLAY_HATCH_STYLE_32  33122
#define ID_MENU_OVERLAY_HATCH_STYLE_33  33123
#define ID_MENU_OVERLAY_HATCH_STYLE_34  33124
#define ID_MENU_OVERLAY_HATCH_STYLE_35  33125
#define ID_MENU_OVERLAY_HATCH_STYLE_36  33126
#define ID_MENU_OVERLAY_HATCH_STYLE_37  33127
#define ID_MENU_OVERLAY_HATCH_STYLE_38  33128
#define ID_MENU_OVERLAY_HATCH_STYLE_39  33129
#define ID_MENU_OVERLAY_HATCH_STYLE_40  33130
#define ID_MENU_OVERLAY_HATCH_STYLE_41  33131
#define ID_MENU_OVERLAY_HATCH_STYLE_42  33132
#define ID_MENU_OVERLAY_HATCH_STYLE_43  33133
#define ID_MENU_OVERLAY_HATCH_STYLE_44  33134
#define ID_MENU_OVERLAY_HATCH_STYLE_45  33135
#define ID_MENU_OVERLAY_HATCH_STYLE_46  33136
#define ID_MENU_OVERLAY_HATCH_STYLE_47  33137
#define ID_MENU_OVERLAY_HATCH_STYLE_48  33138
#define ID_MENU_OVERLAY_HATCH_STYLE_49  33139
#define ID_MENU_OVERLAY_HATCH_STYLE_50  33140
#define ID_MENU_OVERLAY_HATCH_STYLE_51  33141
#define ID_MENU_OVERLAY_HATCH_STYLE_52  33142
#define ID_MENU_OVERLAY_GARDIENT_COLOR  33143
#define ID_MENU_OVERLAY_GARDIENT_BLENDPOS 33144
#define ID_MENU_OVERLAY_GARDIENT_LINERMODE 33145
#define ID_MENU_OVERLAY_GARDIENT_LINERMODE_0 33146
#define ID_MENU_OVERLAY_GARDIENT_LINERMODE_1 33147
#define ID_MENU_OVERLAY_GARDIENT_LINERMODE_2 33148
#define ID_MENU_OVERLAY_GARDIENT_LINERMODE_3 33149
#define ID_MENU_OVERLAY_LINESTRIPE_STYLE 33150
#define ID_MENU_OVERLAY_LINESTRIPE_STYLE_0 33151
#define ID_MENU_OVERLAY_LINESTRIPE_STYLE_1 33152
#define ID_MENU_OVERLAY_LINESTRIPE_STYLE_2 33153
#define ID_MENU_OVERLAY_LINESTRIPE_STYLE_3 33154
#define ID_MENU_OVERLAY_LINESTRIPE_STYLE_4 33155
#define ID_MENU_OVERLAY_LINECAP_STYLE   33156
#define ID_MENU_OVERLAY_LINECAP_STYLE_0 33157
#define ID_MENU_OVERLAY_LINECAP_STYLE_1 33158
#define ID_MENU_OVERLAY_LINECAP_STYLE_2 33159
#define ID_MENU_OVERLAY_LINEALIGNMENT_STYLE 33160
#define ID_MENU_OVERLAY_LINEALIGNMENT_STYLE_0 33161
#define ID_MENU_OVERLAY_LINEALIGNMENT_STYLE_1 33162
#define ID_MENU_OVERLAY_LINEJOIN_STYLE  33163
#define ID_MENU_OVERLAY_LINEJOIN_STYLE_0 33164
#define ID_MENU_OVERLAY_LINEJOIN_STYLE_1 33165
#define ID_MENU_OVERLAY_LINEJOIN_STYLE_2 33166
#define ID_MENU_OVERLAY_LINEJOIN_STYLE_3 33167
#define ID_MENU_OVERLAY_ARROW_STYLE     33168
#define ID_MENU_OVERLAY_ARROW_STYLE_0   33169
#define ID_MENU_OVERLAY_ARROW_STYLE_1   33170
#define ID_MENU_OVERLAY_ARROW_STYLE_2   33171
#define ID_MENU_OVERLAY_ARROW_STYLE_3   33172
#define ID_MENU_OVERLAY_ARROW_STYLE_4   33173
#define ID_MENU_OVERLAY_ARROW_STYLE_5   33174
#define ID_MENU_OVERLAY_ARROW_STYLE_6   33175
#define ID_MENU_OVERLAY_ARROW_STYLE_7   33176
#define ID_MENU_OVERLAY_ARROW_STYLE_8   33177
#define ID_MENU_OVERLAY_ARROW_STYLE_9   33178
#define ID_MENU_OVERLAY_ARROW_STYLE_10  33179
#define ID_MENU_OVERLAY_ARROW_STYLE_11  33180
#define ID_MENU_OVERLAY_ARROW_STYLE_12  33181
#define ID_MENU_OVERLAY_ARROW_STYLE_13  33182
#define ID_MENU_OVERLAY_ARROW_STYLE_14  33183
#define ID_MENU_OVERLAY_ARROW_STYLE_15  33184
#define ID_MENU_OVERLAY_ARROW_STYLE_16  33185
#define ID_MENU_OVERLAY_ARROW_STYLE_17  33186
#define ID_MENU_OVERLAY_ARROW_STYLE_18  33187
#define ID_MENU_OVERLAY_ARROW_STYLE_19  33188
#define ID_MENU_OVERLAY_ARROW_STYLE_20  33189
#define ID_MENU_OVERLAY_ARROW_STYLE_21  33190
#define ID_MENU_OVERLAY_ARROW_STYLE_22  33191
#define ID_MENU_OVERLAY_ARROW_STYLE_23  33192
#define ID_MENU_OVERLAY_ARROW_STYLE_24  33193
#define ID_MENU_OVERLAY_ARROW_STYLE_25  33194
#define ID_MENU_OVERLAY_ARROW_STYLE_26  33195
#define ID_MENU_OVERLAY_ARROW_STYLE_27  33196
#define ID_MENU_OVERLAY_ARROW_STYLE_28  33197
#define ID_MENU_OVERLAY_ARROW_STYLE_29  33198
#define ID_MENU_OVERLAY_ARROW_STYLE_30  33199
#define ID_MENU_OVERLAY_ARROW_STYLE_31  33200
#define ID_MENU_OVERLAY_ARROW_STYLE_32  33201
#define ID_MENU_OVERLAY_ARROW_STYLE_33  33202
#define ID_MENU_OVERLAY_ARROW_STYLE_34  33203
#define ID_MENU_OVERLAY_ARROW_STYLE_35  33204
#define ID_MENU_OVERLAY_ENDARROW_STYLE  33205
#define ID_MENU_OVERLAY_ENDARROW_STYLE_0 33206
#define ID_MENU_OVERLAY_ENDARROW_STYLE_1 33207
#define ID_MENU_OVERLAY_ENDARROW_STYLE_2 33208
#define ID_MENU_OVERLAY_ENDARROW_STYLE_3 33209
#define ID_MENU_OVERLAY_ENDARROW_STYLE_4 33210
#define ID_MENU_OVERLAY_ENDARROW_STYLE_5 33211
#define ID_MENU_OVERLAY_ENDARROW_STYLE_6 33212
#define ID_MENU_OVERLAY_ENDARROW_STYLE_7 33213
#define ID_MENU_OVERLAY_ENDARROW_STYLE_8 33214
#define ID_MENU_OVERLAY_ENDARROW_STYLE_9 33215
#define ID_MENU_OVERLAY_ENDARROW_STYLE_10 33216
#define ID_MENU_OVERLAY_ENDARROW_STYLE_11 33217
#define ID_MENU_OVERLAY_ENDARROW_STYLE_12 33218
#define ID_MENU_OVERLAY_ENDARROW_STYLE_13 33219
#define ID_MENU_OVERLAY_ENDARROW_STYLE_14 33220
#define ID_MENU_OVERLAY_ENDARROW_STYLE_15 33221
#define ID_MENU_OVERLAY_ENDARROW_STYLE_16 33222
#define ID_MENU_OVERLAY_ENDARROW_STYLE_17 33223
#define ID_MENU_OVERLAY_ENDARROW_STYLE_18 33224
#define ID_MENU_OVERLAY_ENDARROW_STYLE_19 33225
#define ID_MENU_OVERLAY_ENDARROW_STYLE_20 33226
#define ID_MENU_OVERLAY_ENDARROW_STYLE_21 33227
#define ID_MENU_OVERLAY_ENDARROW_STYLE_22 33228
#define ID_MENU_OVERLAY_ENDARROW_STYLE_23 33229
#define ID_MENU_OVERLAY_ENDARROW_STYLE_24 33230
#define ID_MENU_OVERLAY_ENDARROW_STYLE_25 33231
#define ID_MENU_OVERLAY_ENDARROW_STYLE_26 33232
#define ID_MENU_OVERLAY_ENDARROW_STYLE_27 33233
#define ID_MENU_OVERLAY_ENDARROW_STYLE_28 33234
#define ID_MENU_OVERLAY_ENDARROW_STYLE_29 33235
#define ID_MENU_OVERLAY_ENDARROW_STYLE_30 33236
#define ID_MENU_OVERLAY_ENDARROW_STYLE_31 33237
#define ID_MENU_OVERLAY_ENDARROW_STYLE_32 33238
#define ID_MENU_OVERLAY_ENDARROW_STYLE_33 33239
#define ID_MENU_OVERLAY_ENDARROW_STYLE_34 33240
#define ID_MENU_OVERLAY_ENDARROW_STYLE_35 33241
#define ID_MENU_OVERLAY_TEXT_STRING     33242
#define ID_MENU_OVERLAY_TEXT_ALIGNTOP   33243
#define ID_MENU_OVERLAY_TEXT_ALIGNYCENTER 33244
#define ID_MENU_OVERLAY_TEXT_ALIGNBOTTOM 33245
#define ID_MENU_OVERLAY_TEXT_RIGHTTOLEFT 33246
#define ID_MENU_OVERLAY_TEXT_VERTICAL   33247
#define ID_MENU_OVERLAY_TEXT_AUTOBOX    33248
#define ID_MENU_OVERLAY_TEXT_LINEINTERVAL 33249

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        397
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         2916
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
